// 这个文件已经全部加上中文注释
/**
 * Licensed to the Apache Software Foundation (ASF) under one
 * or more contributor license agreements.  See the NOTICE file
 * distributed with this work for additional information
 * regarding copyright ownership.  The ASF licenses this file
 * to you under the Apache License, Version 2.0 (the
 * "License"); you may not use this file except in compliance
 * with the License.  You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package org.apache.hadoop.yarn.server.timeline;

import org.apache.hadoop.classification.InterfaceAudience.Private;
import org.apache.hadoop.classification.InterfaceStability.Unstable;

/**
 * 时间线服务中实体的唯一标识符，通过ID和类型共同标识一个实体
 */
@Private
@Unstable
public class EntityIdentifier implements Comparable<EntityIdentifier> {

  private String id;
  private String type;

  /**
   * 构造实体标识符，通过实体ID和类型共同标识
   * @param id 实体唯一ID
   * @param type 实体类型
   */
  public EntityIdentifier(String id, String type) {
    this.id = id;
    this.type = type;
  }

  /**
   * 获取实体ID
   * @return 实体ID
   */
  public String getId() {
    return id;
  }

  /**
   * 获取实体类型
   * @return 实体类型
   */
  public String getType() {
    return type;
  }

  @Override
  public int compareTo(EntityIdentifier other) {
    // 先比较实体类型
    int c = type.compareTo(other.type);
    if (c != 0) return c;
    // 类型相同再比较实体ID
    return id.compareTo(other.id);
  }

  @Override
  public int hashCode() {
    // generated by eclipse
    final int prime = 31;
    int result = 1;
    result = prime * result + ((id == null) ? 0 : id.hashCode());
    result = prime * result + ((type == null) ? 0 : type.hashCode());
    return result;
  }

  @Override
  public boolean equals(Object obj) {
    // generated by eclipse
    if (this == obj)
      return true;
    if (obj == null)
      return false;
    if (getClass() != obj.getClass())
      return false;
    EntityIdentifier other = (EntityIdentifier) obj;
    if (id == null) {
      if (other.id != null)
        return false;
    } else if (!id.equals(other.id))
      return false;
    if (type == null) {
      if (other.type != null)
        return false;
    } else if (!type.equals(other.type))
      return false;
    return true;
  }

  @Override
  public String toString() {
    return "{ id: " + id + ", type: "+ type + " }";
  }

}